### ISSUE TITLE
why I can Not clone the project with git? 

### ISSUE THREAD

**Issue by lse123** [kdocki/larasign#1]
why I can Not clone the project with git? 

yyyyy@PC8 MINGW64 /f/htdocs_xampp/Design Patterns in PHP and Laravel
**$ git clone git@github.com:kdocki/larasign.git**
Cloning into 'larasign'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.      

Please make sure you have the correct access rights
and the repository exists.

yyyyy@PC8 MINGW64 /f/htdocs_xampp/Design Patterns in PHP and Laravel

**Comment by keizah7** [comment]
@lse123 did you set SSH key in github properly?

Another way would be
`git clone https://github.com/kdocki/larasign.git`

**Comment by kdocki** [comment]
I double checked and this repo is public. You still need to setup your SSH keys in github though if you are cloning over ssh. Or you can do like keizah7 recommended and clone over https.
